const actionsType = {
  REGISTER_SUCCESS: "REGISTER_SUCCESS",
  REGISTER_FAIL: "REGISTER_FAIL",
  LOGIN_SUCCESS: "LOGIN_SUCCESS",
  LOGIN_FAIL: "LOGIN_FAIL",
  LOGOUT: "LOGOUT",

  // App
  GET_CATEGORIES: "GET_CATEGORIES",
  GET_DETAIL_PRODUCT: "GET_DETAIL_PRODUCT",

  // user
  GET_USER: "GET_USER",
};

export default actionsType;
